//latihan 1
#include <iostream.h>
#include <conio.h>

main()
{
cout<<"\n ____________________________________________________________                  ";
cout<<"\n| BBBBBBBBBB    AAAAAAAAAAA  MMMMMMMMMMMMMMMM    ZZZZZZZZZ   |   X    X   X    ";
cout<<"\n| BB      BBB   AA       AA  MM            MM         ZZZ    |     X           ";
cout<<"\n| BB       BB   AA       AA  MM            MM        ZZZ     |   X    X  X     ";
cout<<"\n| BBBBBBBBBB    AAAAAAAAAAA  MM MMMM MMMM  MM       ZZZ      |                 ";
cout<<"\n| BB       BB   AA       AA  MM M  M M  M  MM      ZZZ       |   X     X     X ";
cout<<"\n| BB      BBB   AA       AA  MM M  M M  M  MM     ZZZ        |     X     X     ";
cout<<"\n| BBBBBBBBB     AA       AA  MMMM  MMM  MMMMM    ZZZZZZZZZ   |   X     X    X  ";
cout<<"\n|____________________________________________________________| ";
getch();
}
